### PR TITLE
Fixed issue with last line of pixels being cut off

### PR DESCRIPTION
**Pull request by mymattcarroll**

### CODE REVIEW

**Comment by agilgur5** [comment]
Adding 1 to the diffs would make all signatures have a 1px border (except for 1px width signatures), instead one would want to explicitly check for the 0 case if it occurs (simple `|| 1` would probably suffice).

This is quite an edge case, so I'm also not sure if it makes more sense to throw in this case? I think the behavior you intended probably aligns more with expectations though.

Do note this library isn't just for signatures.

**Comment by mymattcarroll** [comment]
The comment in code is just an extreme example of what was previously happening. 

When i was using this library before making the change, the last pixel line of the bottom and the right of the image was always being trimmed off. E.g. If I have an image that is 5 pixels high and wide and i called `trimCanvas()` 5 times, i would have no image left.

**Comment by agilgur5** [comment]
Oh I see -- there's a one off error since it's a difference. Thanks for clarifying! Feel like I have seen it do that now that I think about it

**Comment by mymattcarroll** [comment]
No problem.

I can see how the word "signature" is a bit strange. Thats just what I was working on at the time. 

Please feel free to change the comment. Or I can change it if you would like to get this merged?

**Comment by agilgur5** [comment]
Yea makes sense as that's what I made this for anyway -- rebased in as f0e62be3a103f3e1aa2d713c64339b110e93257f and published as `0.1.2` :) Thanks for the contribution!

**Pull request closed without merging**
